/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro1p1_diegomaradiaga;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author df346
 */
public class OpcionCancion extends javax.swing.JFrame {
    
    ArrayList<Cancion> ListaCanciones = new ArrayList();
    private int modindex;
    
    /**
     * Creates new form OpcionCancion
     */
    public OpcionCancion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Modificar_Cancion = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtf_CampoCancion = new javax.swing.JTextField();
        jtf_CampoAlbum = new javax.swing.JTextField();
        jtf_CampoArtista = new javax.swing.JTextField();
        GuardarCambios = new javax.swing.JButton();
        jFormattedCampoDuracion = new javax.swing.JFormattedTextField();
        jFormattedCampoLanzamiento1 = new javax.swing.JFormattedTextField();
        Panel_Labotify = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Informacion = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(263, 392));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("modificación");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Año de lanzamiento : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/configuraciones.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Centro de");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Duración (en segundos) :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Artista : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Álbum : ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Canción :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jtf_CampoCancion.setBackground(new java.awt.Color(255, 255, 255));
        jtf_CampoCancion.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jtf_CampoCancion.setForeground(new java.awt.Color(0, 0, 0));
        jtf_CampoCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_CampoCancionActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_CampoCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 240, -1));

        jtf_CampoAlbum.setBackground(new java.awt.Color(255, 255, 255));
        jtf_CampoAlbum.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jtf_CampoAlbum.setForeground(new java.awt.Color(0, 0, 0));
        jtf_CampoAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_CampoAlbumActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_CampoAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 240, -1));

        jtf_CampoArtista.setBackground(new java.awt.Color(255, 255, 255));
        jtf_CampoArtista.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jtf_CampoArtista.setForeground(new java.awt.Color(0, 0, 0));
        jtf_CampoArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_CampoArtistaActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_CampoArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, -1));

        GuardarCambios.setBackground(new java.awt.Color(51, 102, 255));
        GuardarCambios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GuardarCambios.setForeground(new java.awt.Color(255, 255, 255));
        GuardarCambios.setText("Guardar Cambios");
        GuardarCambios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        GuardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarCambiosMouseClicked(evt);
            }
        });
        GuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCambiosActionPerformed(evt);
            }
        });
        jPanel2.add(GuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 120, 30));

        jFormattedCampoDuracion.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedCampoDuracion.setForeground(new java.awt.Color(0, 0, 0));
        jFormattedCampoDuracion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel2.add(jFormattedCampoDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 240, 30));

        jFormattedCampoLanzamiento1.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedCampoLanzamiento1.setForeground(new java.awt.Color(0, 0, 0));
        jFormattedCampoLanzamiento1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel2.add(jFormattedCampoLanzamiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 352, 240, 30));

        javax.swing.GroupLayout Modificar_CancionLayout = new javax.swing.GroupLayout(Modificar_Cancion.getContentPane());
        Modificar_Cancion.getContentPane().setLayout(Modificar_CancionLayout);
        Modificar_CancionLayout.setHorizontalGroup(
            Modificar_CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Modificar_CancionLayout.setVerticalGroup(
            Modificar_CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificar_CancionLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Labotify.setBackground(new java.awt.Color(78, 71, 115));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reproductor-de-musica.png"))); // NOI18N
        jLabel1.setText("Labotify");

        Agregar.setBackground(new java.awt.Color(78, 71, 115));
        Agregar.setForeground(new java.awt.Color(255, 255, 255));
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Agregar.png"))); // NOI18N
        Agregar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Agregar.setContentAreaFilled(false);
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Listar.setForeground(new java.awt.Color(255, 255, 255));
        Listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Listar.png"))); // NOI18N
        Listar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Listar.setContentAreaFilled(false);
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });

        Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Modificar.png"))); // NOI18N
        Modificar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Modificar.setContentAreaFilled(false);
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Informacion.setForeground(new java.awt.Color(255, 255, 255));
        Informacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Info.png"))); // NOI18N
        Informacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Informacion.setContentAreaFilled(false);
        Informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacionActionPerformed(evt);
            }
        });

        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Eliminar.png"))); // NOI18N
        Eliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Eliminar.setContentAreaFilled(false);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Menu.png"))); // NOI18N
        Menu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menú", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Menu.setContentAreaFilled(false);
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Panel_LabotifyLayout = new javax.swing.GroupLayout(Panel_Labotify);
        Panel_Labotify.setLayout(Panel_LabotifyLayout);
        Panel_LabotifyLayout.setHorizontalGroup(
            Panel_LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LabotifyLayout.createSequentialGroup()
                .addGroup(Panel_LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_LabotifyLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_LabotifyLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(Panel_LabotifyLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(Panel_LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_LabotifyLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Panel_LabotifyLayout.setVerticalGroup(
            Panel_LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LabotifyLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(Panel_LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(Panel_LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(Panel_LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Labotify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Labotify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        String cancion = (JOptionPane.showInputDialog(this, "Ingrese el nombre de la cancion: ",JOptionPane.QUESTION_MESSAGE));
        String album = (JOptionPane.showInputDialog(this, "Ingrese el nombre del álbum: ",JOptionPane.QUESTION_MESSAGE));
        String artista = (JOptionPane.showInputDialog(this, "Ingrese el nombre del artista: ",JOptionPane.QUESTION_MESSAGE));
        int duracion = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la duracion de la cancion (segundos): ",JOptionPane.QUESTION_MESSAGE));
        int lanzamiento = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el año de lanzamiento de la canción: ",JOptionPane.QUESTION_MESSAGE));       
        
        ListaCanciones.add(new Cancion(cancion, album, artista, duracion, lanzamiento));
        JOptionPane.showMessageDialog(this, "Se agregó correctamente");
    }//GEN-LAST:event_AgregarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        int cont = 1;
        String linea = "";
        for (int i = 0; i < ListaCanciones.size(); i++) {
            linea += cont + ") " + ListaCanciones.get(i).getCancion() + " - " + ListaCanciones.get(i).getArtista()+"\n";
            cont++;
        }
        JOptionPane.showMessageDialog(this, linea);


    }//GEN-LAST:event_ListarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        Modificar_Cancion.setVisible(true);
        Modificar_Cancion.setSize(300, 496);
        Modificar_Cancion.setLocationRelativeTo(this);
         
        this.dispose();
        ModCancion();
       
    }//GEN-LAST:event_ModificarActionPerformed

    private void InformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacionActionPerformed
        int cont = 1;
        String linea = "";
        for (int i = 0; i < ListaCanciones.size(); i++) {
            linea += cont + ") " + ListaCanciones.get(i).getCancion() + " - " + ListaCanciones.get(i).getArtista() + "\n";
            cont++;
        }
        int indice =0;
            indice = Integer.parseInt(JOptionPane.showInputDialog(this, linea + ""
                + ""
                + "Ingrese el índice de la canción que desea ver la información: "));
        while(indice>ListaCanciones.size()||indice<=0){
            indice = Integer.parseInt(JOptionPane.showInputDialog(this, linea + ""
                + "¡Cuidado, índice fuera de rango!\n"
                + "Ingrese el índice de la canción que desea ver la información: "));
        }
         JOptionPane.showMessageDialog(this, "Cancion: " + ListaCanciones.get(indice - 1).getCancion() + "\n"
                + "Album: " + ListaCanciones.get(indice - 1).getAlbum() + "\n"
                + "Artista: " + ListaCanciones.get(indice - 1).getArtista() + "\n"
                + "Duracion: " + ListaCanciones.get(indice - 1).getDuracion() + " segundos"+"\n"
                + "Año de lanzamiento: " + ListaCanciones.get(indice - 1).getLanzamiento() + "\n");
       
    }//GEN-LAST:event_InformacionActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int cont = 1;
        String linea = "";
        for (int i = 0; i < ListaCanciones.size(); i++) {
            linea += cont + ") " + ListaCanciones.get(i).getCancion() + " - " + ListaCanciones.get(i).getArtista() + "\n";
            cont++;
        }
//        int cont = 0;
//        String linea = "";
//        for (int i = 0; i < ListaCanciones.size(); i++) {
//            linea += cont + ") " + ListaCanciones.get(i).getCancion() + " - " + ListaCanciones.get(i).getArtista()+"\n";
//            cont++;
//        }
        int indice =0;
            indice = Integer.parseInt(JOptionPane.showInputDialog(this, linea + ""
                + ""
                + "Ingrese el índice de la canción que desea eliminar: "));
        while(indice>ListaCanciones.size()||indice<=0){
            indice = Integer.parseInt(JOptionPane.showInputDialog(this, linea + ""
                + "¡Cuidado, índice fuera de rango!\n"
                + "Ingrese el índice de la canción que desea eliminar: "));
        }
        
//        int indice = 0;
//            indice = Integer.parseInt(JOptionPane.showInputDialog(this, linea+""
//                + ""
//                + "Ingrese el índice de la canción que desea eliminar: "));
//        while(indice>ListaCanciones.size()){
//            indice = Integer.parseInt(JOptionPane.showInputDialog(this, linea + ""
//                + "\n"
//                + "¡Cuidado, índice fuera de rango!\n"
//                + "Ingrese el índice de la canción que desea eliminar: ", JOptionPane.WARNING_MESSAGE));
//        }
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de que quiere eliminar " + ListaCanciones.get(indice-1).getCancion()+" ?", "Advertencia", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (resp == 0){
            ListaCanciones.remove(indice-1);
            JOptionPane.showMessageDialog(this, "Se eliminó correctamente");
        }
        if (resp == 1){
            JOptionPane.showMessageDialog(null, "Nice");
        }
       
    }//GEN-LAST:event_EliminarActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        Menu M = new Menu();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void jtf_CampoCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_CampoCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_CampoCancionActionPerformed

    private void jtf_CampoAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_CampoAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_CampoAlbumActionPerformed

    private void jtf_CampoArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_CampoArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_CampoArtistaActionPerformed

    private void GuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCambiosActionPerformed
        
        ListaCanciones.get(modindex-1).setCancion(jtf_CampoCancion.getText());
        ListaCanciones.get(modindex-1).setAlbum(jtf_CampoAlbum.getText());
        ListaCanciones.get(modindex-1).setArtista(jtf_CampoArtista.getText());
        ListaCanciones.get(modindex-1).setDuracion(Integer.parseInt(jFormattedCampoDuracion.getText()));
        ListaCanciones.get(modindex-1).setLanzamiento(Integer.parseInt(jFormattedCampoLanzamiento1.getText()));        
        
        JOptionPane.showMessageDialog(this, "El cambio se guardó existosamente");
        jtf_CampoCancion.setText("");
        jtf_CampoAlbum.setText("");
        jtf_CampoArtista.setText("");
        jFormattedCampoDuracion.setText("");
        jFormattedCampoLanzamiento1.setText("");
        
        Modificar_Cancion.dispose();
        this.setVisible(true);
              
    }//GEN-LAST:event_GuardarCambiosActionPerformed

    private void GuardarCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarCambiosMouseClicked
        
    }//GEN-LAST:event_GuardarCambiosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionCancion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton GuardarCambios;
    private javax.swing.JButton Informacion;
    private javax.swing.JButton Listar;
    private javax.swing.JButton Menu;
    private javax.swing.JButton Modificar;
    private javax.swing.JFrame Modificar_Cancion;
    private javax.swing.JPanel Panel_Labotify;
    private javax.swing.JFormattedTextField jFormattedCampoDuracion;
    private javax.swing.JFormattedTextField jFormattedCampoLanzamiento1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtf_CampoAlbum;
    private javax.swing.JTextField jtf_CampoArtista;
    private javax.swing.JTextField jtf_CampoCancion;
    // End of variables declaration//GEN-END:variables
    
    int indice = 0;
    String cancion = "";
    String album = "";
    String artista = "";
    
    public void ModCancion(){
        int cont = 1;
        String linea = "";
        for (int i = 0; i < ListaCanciones.size(); i++) {
            linea += cont + ") " + ListaCanciones.get(i).getCancion() + " - " + ListaCanciones.get(i).getArtista() + "\n";
            cont++;
        }
        modindex = Integer.parseInt(JOptionPane.showInputDialog(this, linea + ""
                + ""
                + "Ingrese el índice de la canción que desea mOdificar: "));
        while(modindex>ListaCanciones.size()||modindex<=0){
            modindex = Integer.parseInt(JOptionPane.showInputDialog(this, linea + ""
                + "¡Cuidado, índice fuera de rango!\n"
                + "Ingrese el índice de la canción que desea modificar: "));
        }
//        int cont = 0;
//        String linea = "";
//        for (int i = 0; i < ListaCanciones.size(); i++) {
//            linea += cont + ") " + ListaCanciones.get(i).getCancion() + " - " + ListaCanciones.get(i).getArtista() + "\n";
//            cont++;
//        }
//        
//        modindex = Integer.parseInt(JOptionPane.showInputDialog(this, linea + ""
//                + ""
//                + "Ingrese el índice de la canción que desea modificar: "));
//        while (modindex > ListaCanciones.size()) {
//            modindex = Integer.parseInt(JOptionPane.showInputDialog(this, linea + ""
//                    + "¡Cuidado, índice fuera de rango!\n"
//                    + "Ingrese un índice correcto de la canción que modficar: ", JOptionPane.WARNING_MESSAGE));
//        }
        Modificar_Cancion.setVisible(true);

        jtf_CampoCancion.setText(ListaCanciones.get(modindex-1).getCancion());
        jtf_CampoAlbum.setText(ListaCanciones.get(modindex-1).getAlbum());
        jtf_CampoArtista.setText(ListaCanciones.get(modindex-1).getArtista());
        jFormattedCampoDuracion.setValue(ListaCanciones.get(modindex-1).getDuracion());
        jFormattedCampoLanzamiento1.setValue(ListaCanciones.get(modindex-1).getLanzamiento());
             
    }
}
